api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: api--password
        value: '{{ securedParameter "ApiPassword" }}'
      - name: api--username
        value: '{{ securedParameter "ApiUsername" }}'
      - name: connectionstrings--cache
        value: cache:6379
      - name: connectionstrings--postgresdb
        value: '{{ secretOutput "SERVICE_BINDING_KVD0D4074E_ENDPOINT" "connectionString" }};Database=demoApp'
  template:
    containers:
      - image: {{ .Image }}
        name: api
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: Api__IntegrationApiBaseUrl
            value: '{{ parameter "ApiBaseUrl" }}'
          - name: Auth0__Audience
            value: '{{ parameter "Auth0Audience" }}'
          - name: Auth0__Domain
            value: '{{ parameter "Auth0Domain" }}'
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: Api__Password
            secretRef: api--password
          - name: Api__Username
            secretRef: api--username
          - name: ConnectionStrings__cache
            secretRef: connectionstrings--cache
          - name: ConnectionStrings__postgresDb
            secretRef: connectionstrings--postgresdb
    scale:
      minReplicas: 1
tags:
  azd-service-name: api
  aspire-resource-name: api
