api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: 3000
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    containers:
      - image: {{ .Image }}
        name: frontend
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: BROWSER
            value: none
          - name: NODE_ENV
            value: development
          - name: REACT_APP_API_BASE_URL
            value: http://api.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: REACT_APP_AUTH0_AUDIENCE
            value: '{{ parameter "Auth0Audience" }}'
          - name: REACT_APP_AUTH0_CLIENTID
            value: '{{ parameter "Auth0ClientId" }}'
          - name: REACT_APP_AUTH0_DOMAIN
            value: '{{ parameter "Auth0Domain" }}'
          - name: SERVER_PORT
            value: "3000"
    scale:
      minReplicas: 1
tags:
  azd-service-name: frontend
  aspire-resource-name: frontend
